version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
  redis:
    image: "redis:alpine"
    command: redis-server
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis:/var/lib/redis
